### PR TITLE
Separate resolvers for queries and mutations

### PR DESCRIPTION
**Pull request by sanae10001**
See https://github.com/graph-gophers/graphql-go/issues/145

### CODE REVIEW

**Comment by sanae10001** [comment]
```
github.com/graph-gophers/graphql-go (download)
github.com/opentracing/opentracing-go (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
graphql.go:10:2: use of internal package not allowed
graphql.go:11:2: use of internal package not allowed
graphql.go:12:2: use of internal package not allowed
graphql.go:13:2: use of internal package not allowed
graphql.go:14:2: use of internal package not allowed
graphql.go:15:2: use of internal package not allowed
graphql.go:16:2: use of internal package not allowed
internal/exec/exec.go:11:2: use of internal package not allowed
internal/exec/exec.go:12:2: use of internal package not allowed
internal/exec/exec.go:13:2: use of internal package not allowed
internal/exec/exec.go:14:2: use of internal package not allowed
internal/exec/exec.go:15:2: use of internal package not allowed
internal/exec/packer/packer.go:10:2: use of internal package not allowed
internal/exec/packer/packer.go:11:2: use of internal package not allowed
internal/exec/resolvable/meta.go:7:2: use of internal package not allowed
internal/exec/resolvable/resolvable.go:12:2: use of internal package not allowed
internal/exec/resolvable/meta.go:8:2: use of internal package not allowed
internal/exec/selected/selected.go:9:2: use of internal package not allowed
internal/exec/selected/selected.go:10:2: use of internal package not allowed
internal/exec/selected/selected.go:11:2: use of internal package not allowed
internal/exec/selected/selected.go:12:2: use of internal package not allowed
internal/exec/selected/selected.go:13:2: use of internal package not allowed
internal/query/query.go:9:2: use of internal package not allowed
internal/schema/schema.go:9:2: use of internal package not allowed
internal/validation/validation.go:12:2: use of internal package not allowed
internal/validation/validation.go:13:2: use of internal package not allowed
internal/validation/validation.go:14:2: use of internal package not allowed
introspection/introspection.go:6:2: use of internal package not allowed
introspection/introspection.go:7:2: use of internal package not allowed
```
What happened?

**Comment by GhostRussia** [comment]
This change will break compatibility and many people will have to rewrite their code.
I don't want a repeat of the story > https://github.com/satori/go.uuid/issues/66

**Comment by tonyghita** [comment]
@sanae10001 are you still working within `$GOPATH/src/github.com/neelance/graphql-go`? You probably want to update your working directory.

@GhostRussia there may be some way that we can provide the new functionality without breaking clients (i.e. via some option or some temporary cleverness in the resolver lookup code).

Either way, we'll want to ensure we communicate the changes and impact of the changes before merging this in.

**Comment by GhostRussia** [comment]
I think can use the interface to determine the type of resolver. 
###### (I'm not sure that the code works, it's just a pseudocode)
```patch
From 716eca2b4682a91c7043dab5655cafe2a98e35a1 Mon Sep 17 00:00:00 2001

---
 internal/exec/resolvable/resolvable.go | 26 +++++++++++++++++++++++---
 1 file changed, 23 insertions(+), 3 deletions(-)

diff --git a/internal/exec/resolvable/resolvable.go b/internal/exec/resolvable/resolvable.go
index b7c1d93..8cdb689 100644
--- a/internal/exec/resolvable/resolvable.go
+++ b/internal/exec/resolvable/resolvable.go
@@ -54,19 +54,39 @@ func (*Object) isResolvable() {}
 func (*List) isResolvable()   {}
 func (*Scalar) isResolvable() {}
 
+
+type SeparateResolver interface {
+	Query() interface{}
+	Mutation() interface{}
+}
+
 func ApplyResolver(s *schema.Schema, resolver interface{}) (*Schema, error) {
 	b := newBuilder(s)
 
-	var query, mutation Resolvable
+	var (
+		query, mutation                 Resolvable
+		queryResolver, mutationResolver interface{}
+	)
+
+	sr, isSeparateResolver := resolver.(SeparateResolver)
+
+	if isSeparateResolver {
+		// separate resolver
+		queryResolver = sr.Query()
+		mutationResolver = sr.Mutation()
+	} else {
+		// old resolver
+		queryResolver = resolver
+		mutationResolver = resolver
+	}
 
 	if t, ok := s.EntryPoints["query"]; ok {
-		if err := b.assignExec(&query, t, reflect.TypeOf(resolver)); err != nil {
+		if err := b.assignExec(&query, t, reflect.TypeOf(queryResolver)); err != nil {
 			return nil, err
 		}
 	}
 
 	if t, ok := s.EntryPoints["mutation"]; ok {
-		if err := b.assignExec(&mutation, t, reflect.TypeOf(resolver)); err != nil {
+		if err := b.assignExec(&mutation, t, reflect.TypeOf(mutationResolver)); err != nil {
 			return nil, err
 		}
 	}
-- 
```

And when using interfaces, we do not have to do extra reflection
```go
rFunc := root.MethodByName("Query")
if !rFunc.IsValid() {
	return nil, errors.New("not found query resolver")
}
 
queryResolver = rFunc.Call(nil)[0]
```

**Comment by GhostRussia** [comment]
I checked here, this code allows working with two versions of resolvers. Original tests pass.

```patch
---
 internal/exec/exec.go                  | 12 +++++++++-
 internal/exec/resolvable/resolvable.go | 42 +++++++++++++++++++++++++---------
 2 files changed, 42 insertions(+), 12 deletions(-)

diff --git a/internal/exec/exec.go b/internal/exec/exec.go
index f714961..88d44f5 100644
--- a/internal/exec/exec.go
+++ b/internal/exec/exec.go
@@ -40,7 +40,17 @@ func (r *Request) Execute(ctx context.Context, s *resolvable.Schema, op *query.O
 	func() {
 		defer r.handlePanic(ctx)
 		sels := selected.ApplyOperation(&r.Request, s, op)
-		r.execSelections(ctx, sels, nil, s.Resolver, &out, op.Type == query.Mutation)
+
+		var resolver reflect.Value
+			switch op.Type {
+				case query.Query:
+					resolver = s.QueryResolver
+				case query.Mutation:
+				resolver = s.MutationResolver
+				default:
+				panic("unknown query operation")
+				}
+				r.execSelections(ctx, sels, nil, resolver, &out, op.Type == query.Mutation)
 	}()
 
 	if err := ctx.Err(); err != nil {
diff --git a/internal/exec/resolvable/resolvable.go b/internal/exec/resolvable/resolvable.go
index b7c1d93..004de94 100644
--- a/internal/exec/resolvable/resolvable.go
+++ b/internal/exec/resolvable/resolvable.go
@@ -5,7 +5,6 @@ import (
 	"fmt"
 	"reflect"
 	"strings"
-
 	"github.com/graph-gophers/graphql-go/internal/common"
 	"github.com/graph-gophers/graphql-go/internal/exec/packer"
 	"github.com/graph-gophers/graphql-go/internal/schema"
@@ -13,9 +12,10 @@ import (
 
 type Schema struct {
 	schema.Schema
-	Query    Resolvable
-	Mutation Resolvable
-	Resolver reflect.Value
+	Query            Resolvable
+	Mutation         Resolvable
+	QueryResolver    reflect.Value
+	MutationResolver reflect.Value
 }
 
 type Resolvable interface {
@@ -54,19 +54,38 @@ func (*Object) isResolvable() {}
 func (*List) isResolvable()   {}
 func (*Scalar) isResolvable() {}
 
+type SeparateResolver interface {
+	Query() interface{}
+	Mutation() interface{}
+}
+
 func ApplyResolver(s *schema.Schema, resolver interface{}) (*Schema, error) {
 	b := newBuilder(s)
 
-	var query, mutation Resolvable
+	var (
+		query, mutation                 Resolvable
+		queryResolver, mutationResolver reflect.Value
+	)
+
+	sr, isSeparateResolver := resolver.(SeparateResolver)
+
+	if isSeparateResolver {
+		queryResolver = reflect.ValueOf(sr.Query())
+		mutationResolver = reflect.ValueOf(sr.Mutation())
+	} else {
+		value := reflect.ValueOf(resolver)
+		queryResolver = value
+		mutationResolver = value
+	}
 
 	if t, ok := s.EntryPoints["query"]; ok {
-		if err := b.assignExec(&query, t, reflect.TypeOf(resolver)); err != nil {
+		if err := b.assignExec(&query, t, queryResolver.Type()); err != nil {
 			return nil, err
 		}
 	}
 
 	if t, ok := s.EntryPoints["mutation"]; ok {
-		if err := b.assignExec(&mutation, t, reflect.TypeOf(resolver)); err != nil {
+		if err := b.assignExec(&mutation, t, mutationResolver.Type()); err != nil {
 			return nil, err
 		}
 	}
@@ -76,10 +95,11 @@ func ApplyResolver(s *schema.Schema, resolver interface{}) (*Schema, error) {
 	}
 
 	return &Schema{
-		Schema:   *s,
-		Resolver: reflect.ValueOf(resolver),
-		Query:    query,
-		Mutation: mutation,
+		Schema:           *s,
+		Query:            query,
+		Mutation:         mutation,
+		QueryResolver:    queryResolver,
+		MutationResolver: mutationResolver,
 	}, nil
 }
 
-- 
```

**Comment by GhostRussia** [comment]
After adapting @sanae10001 tests, I decided to split the interfaces

full resolvers patch:
```patch
From f78d920327dd738dd91ccb16a9fe78fe59a4908b Mon Sep 17 00:00:00 2001
From: Vladislav Fursov <ghostrussian@gmail.com>
Date: Fri, 16 Mar 2018 06:12:06 +0900
Subject: [PATCH] separate resolver

---
 internal/exec/exec.go                  | 12 ++++++++-
 internal/exec/resolvable/resolvable.go | 48 ++++++++++++++++++++++++++--------
 2 files changed, 48 insertions(+), 12 deletions(-)

diff --git a/internal/exec/exec.go b/internal/exec/exec.go
index f714961..88d44f5 100644
--- a/internal/exec/exec.go
+++ b/internal/exec/exec.go
@@ -40,7 +40,17 @@ func (r *Request) Execute(ctx context.Context, s *resolvable.Schema, op *query.O
 	func() {
 		defer r.handlePanic(ctx)
 		sels := selected.ApplyOperation(&r.Request, s, op)
-		r.execSelections(ctx, sels, nil, s.Resolver, &out, op.Type == query.Mutation)
+
+		var resolver reflect.Value
+			switch op.Type {
+				case query.Query:
+					resolver = s.QueryResolver
+				case query.Mutation:
+				resolver = s.MutationResolver
+				default:
+				panic("unknown query operation")
+				}
+				r.execSelections(ctx, sels, nil, resolver, &out, op.Type == query.Mutation)
 	}()
 
 	if err := ctx.Err(); err != nil {
diff --git a/internal/exec/resolvable/resolvable.go b/internal/exec/resolvable/resolvable.go
index b7c1d93..970aef6 100644
--- a/internal/exec/resolvable/resolvable.go
+++ b/internal/exec/resolvable/resolvable.go
@@ -5,7 +5,6 @@ import (
 	"fmt"
 	"reflect"
 	"strings"
-
 	"github.com/graph-gophers/graphql-go/internal/common"
 	"github.com/graph-gophers/graphql-go/internal/exec/packer"
 	"github.com/graph-gophers/graphql-go/internal/schema"
@@ -13,9 +12,10 @@ import (
 
 type Schema struct {
 	schema.Schema
-	Query    Resolvable
-	Mutation Resolvable
-	Resolver reflect.Value
+	Query            Resolvable
+	Mutation         Resolvable
+	QueryResolver    reflect.Value
+	MutationResolver reflect.Value
 }
 
 type Resolvable interface {
@@ -54,19 +54,44 @@ func (*Object) isResolvable() {}
 func (*List) isResolvable()   {}
 func (*Scalar) isResolvable() {}
 
+type Queryer interface {
+	Query() interface{}
+}
+
+type Mutationer interface {
+	Mutation() interface{}
+}
+
 func ApplyResolver(s *schema.Schema, resolver interface{}) (*Schema, error) {
 	b := newBuilder(s)
 
-	var query, mutation Resolvable
+	var (
+		query, mutation                 Resolvable
+		queryResolver, mutationResolver reflect.Value
+	)
+
+	sqr, isSeparateQueryResolver := resolver.(Queryer)
+	if isSeparateQueryResolver {
+		queryResolver = reflect.ValueOf(sqr.Query())
+	} else {
+		queryResolver = reflect.ValueOf(resolver)
+	}
+
+	smr, isSeparateMutationResolver := resolver.(Mutationer)
+	if isSeparateMutationResolver {
+		mutationResolver = reflect.ValueOf(smr.Mutation())
+	} else {
+		mutationResolver = reflect.ValueOf(resolver)
+	}
 
 	if t, ok := s.EntryPoints["query"]; ok {
-		if err := b.assignExec(&query, t, reflect.TypeOf(resolver)); err != nil {
+		if err := b.assignExec(&query, t, queryResolver.Type()); err != nil {
 			return nil, err
 		}
 	}
 
 	if t, ok := s.EntryPoints["mutation"]; ok {
-		if err := b.assignExec(&mutation, t, reflect.TypeOf(resolver)); err != nil {
+		if err := b.assignExec(&mutation, t, mutationResolver.Type()); err != nil {
 			return nil, err
 		}
 	}
@@ -76,10 +101,11 @@ func ApplyResolver(s *schema.Schema, resolver interface{}) (*Schema, error) {
 	}
 
 	return &Schema{
-		Schema:   *s,
-		Resolver: reflect.ValueOf(resolver),
-		Query:    query,
-		Mutation: mutation,
+		Schema:           *s,
+		Query:            query,
+		Mutation:         mutation,
+		QueryResolver:    queryResolver,
+		MutationResolver: mutationResolver,
 	}, nil
 }
 
-- 
2.16.2
 ```

full tests patch:
```patch
From 89271cdb9f6c30a9afe96732f405858bec30498e Mon Sep 17 00:00:00 2001
From: Vladislav Fursov <ghostrussian@gmail.com>
Date: Fri, 16 Mar 2018 06:12:24 +0900
Subject: [PATCH] separate resolver test

---
 graphql_test.go | 136 +++++++++++++++++++++++++++++++++++++-------------------
 1 file changed, 90 insertions(+), 46 deletions(-)

diff --git a/graphql_test.go b/graphql_test.go
index 1c1bd08..c3da393 100644
--- a/graphql_test.go
+++ b/graphql_test.go
@@ -10,58 +10,92 @@ import (
 	"github.com/graph-gophers/graphql-go/gqltesting"
 )
 
-type helloWorldResolver1 struct{}
+type helloWorldResolver1Root struct{}
+type helloWorldResolver1Query struct{}
 
-func (r *helloWorldResolver1) Hello() string {
+func (r *helloWorldResolver1Root) Query() interface{} {
+	return &helloWorldResolver1Query{}
+}
+
+func (r *helloWorldResolver1Query) Hello() string {
 	return "Hello world!"
 }
 
-type helloWorldResolver2 struct{}
+type helloWorldResolver2Root struct{}
+type helloWorldResolver2Query struct{}
 
-func (r *helloWorldResolver2) Hello(ctx context.Context) (string, error) {
+func (r *helloWorldResolver2Root) Query() interface{} {
+	return &helloWorldResolver2Query{}
+}
+
+func (r *helloWorldResolver2Query) Hello(ctx context.Context) (string, error) {
 	return "Hello world!", nil
 }
 
-type helloSnakeResolver1 struct{}
+type helloSnakeResolver1Root struct{}
+type helloSnakeResolver1Query struct{}
+
+func (r *helloSnakeResolver1Root) Query() interface{} {
+	return &helloSnakeResolver1Query{}
+}
 
-func (r *helloSnakeResolver1) HelloHTML() string {
+func (r *helloSnakeResolver1Query) HelloHTML() string {
 	return "Hello snake!"
 }
 
-func (r *helloSnakeResolver1) SayHello(args struct{ FullName string }) string {
+func (r *helloSnakeResolver1Query) SayHello(args struct{ FullName string }) string {
 	return "Hello " + args.FullName + "!"
 }
 
-type helloSnakeResolver2 struct{}
+type helloSnakeResolver2Root struct{}
+type helloSnakeResolver2Query struct{}
+
+func (r *helloSnakeResolver2Root) Query() interface{} {
+	return &helloSnakeResolver2Query{}
+}
 
-func (r *helloSnakeResolver2) HelloHTML(ctx context.Context) (string, error) {
+func (r *helloSnakeResolver2Query) HelloHTML(ctx context.Context) (string, error) {
 	return "Hello snake!", nil
 }
 
-func (r *helloSnakeResolver2) SayHello(ctx context.Context, args struct{ FullName string }) (string, error) {
+func (r *helloSnakeResolver2Query) SayHello(ctx context.Context, args struct{ FullName string }) (string, error) {
 	return "Hello " + args.FullName + "!", nil
 }
 
-type theNumberResolver struct {
-	number int32
+type theNumberResolverRoot struct{}
+
+type theNumberResolverQuery struct{ number int32 }
+
+type theNumberResolverMutation struct{ number int32 }
+
+func (r *theNumberResolverRoot) Query() interface{} {
+	return &theNumberResolverQuery{}
+}
+
+func (r *theNumberResolverRoot) Mutation() interface{} {
+	return &theNumberResolverMutation{}
 }
 
-func (r *theNumberResolver) TheNumber() int32 {
+func (r *theNumberResolverQuery) TheNumber() int32 {
 	return r.number
 }
 
-func (r *theNumberResolver) ChangeTheNumber(args struct{ NewNumber int32 }) *theNumberResolver {
-	r.number = args.NewNumber
-	return r
+func (r *theNumberResolverMutation) ChangeTheNumber(args struct{ NewNumber int32 }) *theNumberResolverQuery {
+	return &theNumberResolverQuery{number: args.NewNumber}
 }
 
-type timeResolver struct{}
+type timeResolverRoot struct{}
+type timeResolverQuery struct{}
+
+func (r *timeResolverRoot) Query() interface{} {
+	return &timeResolverQuery{}
+}
 
-func (r *timeResolver) AddHour(args struct{ Time graphql.Time }) graphql.Time {
+func (r *timeResolverQuery) AddHour(args struct{ Time graphql.Time }) graphql.Time {
 	return graphql.Time{Time: args.Time.Add(time.Hour)}
 }
 
-var starwarsSchema = graphql.MustParseSchema(starwars.Schema, &starwars.Resolver{})
+var starwarsSchema = graphql.MustParseSchema(starwars.Schema, &starwars.RootResolver{})
 
 func TestHelloWorld(t *testing.T) {
 	gqltesting.RunTests(t, []*gqltesting.Test{
@@ -74,7 +108,7 @@ func TestHelloWorld(t *testing.T) {
 				type Query {
 					hello: String!
 				}
-			`, &helloWorldResolver1{}),
+			`, &helloWorldResolver1Root{}),
 			Query: `
 				{
 					hello
@@ -96,7 +130,7 @@ func TestHelloWorld(t *testing.T) {
 				type Query {
 					hello: String!
 				}
-			`, &helloWorldResolver2{}),
+			`, &helloWorldResolver2Root{}),
 			Query: `
 				{
 					hello
@@ -122,7 +156,7 @@ func TestHelloSnake(t *testing.T) {
 				type Query {
 					hello_html: String!
 				}
-			`, &helloSnakeResolver1{}),
+			`, &helloSnakeResolver1Root{}),
 			Query: `
 				{
 					hello_html
@@ -144,7 +178,7 @@ func TestHelloSnake(t *testing.T) {
 				type Query {
 					hello_html: String!
 				}
-			`, &helloSnakeResolver2{}),
+			`, &helloSnakeResolver2Root{}),
 			Query: `
 				{
 					hello_html
@@ -170,7 +204,7 @@ func TestHelloSnakeArguments(t *testing.T) {
 				type Query {
 					say_hello(full_name: String!): String!
 				}
-			`, &helloSnakeResolver1{}),
+			`, &helloSnakeResolver1Root{}),
 			Query: `
 				{
 					say_hello(full_name: "Rob Pike")
@@ -192,7 +226,7 @@ func TestHelloSnakeArguments(t *testing.T) {
 				type Query {
 					say_hello(full_name: String!): String!
 				}
-			`, &helloSnakeResolver2{}),
+			`, &helloSnakeResolver2Root{}),
 			Query: `
 				{
 					say_hello(full_name: "Rob Pike")
@@ -579,17 +613,22 @@ func TestIncludeDirective(t *testing.T) {
 	})
 }
 
-type testDeprecatedDirectiveResolver struct{}
+type testDeprecatedDirectiveResolverRoot struct{}
+type testDeprecatedDirectiveResolverQuery struct{}
 
-func (r *testDeprecatedDirectiveResolver) A() int32 {
+func (r *testDeprecatedDirectiveResolverRoot) Query() interface{} {
+	return &testDeprecatedDirectiveResolverQuery{}
+}
+
+func (r *testDeprecatedDirectiveResolverQuery) A() int32 {
 	return 0
 }
 
-func (r *testDeprecatedDirectiveResolver) B() int32 {
+func (r *testDeprecatedDirectiveResolverQuery) B() int32 {
 	return 0
 }
 
-func (r *testDeprecatedDirectiveResolver) C() int32 {
+func (r *testDeprecatedDirectiveResolverQuery) C() int32 {
 	return 0
 }
 
@@ -606,7 +645,7 @@ func TestDeprecatedDirective(t *testing.T) {
 					b: Int! @deprecated
 					c: Int! @deprecated(reason: "We don't like it")
 				}
-			`, &testDeprecatedDirectiveResolver{}),
+			`, &testDeprecatedDirectiveResolverRoot{}),
 			Query: `
 				{
 					__type(name: "Query") {
@@ -650,7 +689,7 @@ func TestDeprecatedDirective(t *testing.T) {
 					B @deprecated
 					C @deprecated(reason: "We don't like it")
 				}
-			`, &testDeprecatedDirectiveResolver{}),
+			`, &testDeprecatedDirectiveResolverRoot{}),
 			Query: `
 				{
 					__type(name: "Test") {
@@ -1441,7 +1480,7 @@ func TestMutationOrder(t *testing.T) {
 				type Mutation {
 					changeTheNumber(newNumber: Int!): Query
 				}
-			`, &theNumberResolver{}),
+			`, &theNumberResolverRoot{}),
 			Query: `
 				mutation {
 					first: changeTheNumber(newNumber: 1) {
@@ -1485,7 +1524,7 @@ func TestTime(t *testing.T) {
 				}
 
 				scalar Time
-			`, &timeResolver{}),
+			`, &timeResolverRoot{}),
 			Query: `
 				query($t: Time!) {
 					a: addHour(time: $t)
@@ -1547,29 +1586,34 @@ func TestUnexportedField(t *testing.T) {
 	}
 }
 
-type inputResolver struct{}
+type inputResolverRoot struct{}
+type inputResolverQuery struct{}
+
+func (r *inputResolverRoot) Query() interface{} {
+	return &inputResolverQuery{}
+}
 
-func (r *inputResolver) Int(args struct{ Value int32 }) int32 {
+func (r *inputResolverQuery) Int(args struct{ Value int32 }) int32 {
 	return args.Value
 }
 
-func (r *inputResolver) Float(args struct{ Value float64 }) float64 {
+func (r *inputResolverQuery) Float(args struct{ Value float64 }) float64 {
 	return args.Value
 }
 
-func (r *inputResolver) String(args struct{ Value string }) string {
+func (r *inputResolverQuery) String(args struct{ Value string }) string {
 	return args.Value
 }
 
-func (r *inputResolver) Boolean(args struct{ Value bool }) bool {
+func (r *inputResolverQuery) Boolean(args struct{ Value bool }) bool {
 	return args.Value
 }
 
-func (r *inputResolver) Nullable(args struct{ Value *int32 }) *int32 {
+func (r *inputResolverQuery) Nullable(args struct{ Value *int32 }) *int32 {
 	return args.Value
 }
 
-func (r *inputResolver) List(args struct{ Value []*struct{ V int32 } }) []int32 {
+func (r *inputResolverQuery) List(args struct{ Value []*struct{ V int32 } }) []int32 {
 	l := make([]int32, len(args.Value))
 	for i, entry := range args.Value {
 		l[i] = entry.V
@@ -1577,7 +1621,7 @@ func (r *inputResolver) List(args struct{ Value []*struct{ V int32 } }) []int32
 	return l
 }
 
-func (r *inputResolver) NullableList(args struct{ Value *[]*struct{ V int32 } }) *[]*int32 {
+func (r *inputResolverQuery) NullableList(args struct{ Value *[]*struct{ V int32 } }) *[]*int32 {
 	if args.Value == nil {
 		return nil
 	}
@@ -1590,11 +1634,11 @@ func (r *inputResolver) NullableList(args struct{ Value *[]*struct{ V int32 } })
 	return &l
 }
 
-func (r *inputResolver) Enum(args struct{ Value string }) string {
+func (r *inputResolverQuery) Enum(args struct{ Value string }) string {
 	return args.Value
 }
 
-func (r *inputResolver) NullableEnum(args struct{ Value *string }) *string {
+func (r *inputResolverQuery) NullableEnum(args struct{ Value *string }) *string {
 	return args.Value
 }
 
@@ -1602,7 +1646,7 @@ type recursive struct {
 	Next *recursive
 }
 
-func (r *inputResolver) Recursive(args struct{ Value *recursive }) int32 {
+func (r *inputResolverQuery) Recursive(args struct{ Value *recursive }) int32 {
 	n := int32(0)
 	v := args.Value
 	for v != nil {
@@ -1612,7 +1656,7 @@ func (r *inputResolver) Recursive(args struct{ Value *recursive }) int32 {
 	return n
 }
 
-func (r *inputResolver) ID(args struct{ Value graphql.ID }) graphql.ID {
+func (r *inputResolverQuery) ID(args struct{ Value graphql.ID }) graphql.ID {
 	return args.Value
 }
 
@@ -1648,7 +1692,7 @@ func TestInput(t *testing.T) {
 			Option1
 			Option2
 		}
-	`, &inputResolver{})
+	`, &inputResolverRoot{})
 	gqltesting.RunTests(t, []*gqltesting.Test{
 		{
 			Schema: coercionSchema,
-- 
2.16.2
```

**Comment by GhostRussia** [comment]
https://github.com/graph-gophers/graphql-go/pull/182#issuecomment-373405589
@tonyghita SemaphoreCI still working within $GOPATH/src/github.com/neelance/graphql-go https://semaphoreci.com/neelance/graphql-go/branches/pull-request-182/builds/4

**Comment by tonyghita** [comment]
Looks like we had two webhooks to the SemaphoreCI integration that were racing each other. I removed the old one that pointed to the previous repository, so we shouldn't see these issues.

**Comment by mytototo** [comment]
Hi there,

Is there any ETA regarding this PR?
How do you want to handle backward compatibilities?

Thanks a lot for your contribution.

**Comment by sanae10001** [comment]
@mytototo Now, it don't break compatibility. All above codes can correctly run.

**Comment by mytototo** [comment]
@sanae10001 Ok, thanks a lot.

**Comment by mrg0lden** [comment]
Do you need any help with this PR to get it merged? @pavelnikolov

**Comment by pavelnikolov** [comment]
I'm trying to respond promptly to all new issues and PRs. I'm sorry for the delay on existing PRs. I'll review shortly.

**Comment by pavelnikolov** [comment]
I wonder if this can be done in a way that doesn't introduce a breaking change 🤔

**Comment by sanae10001** [comment]
> I wonder if this can be done in a way that doesn't introduce a breaking change 🤔
It don't break compatibility. All above codes can correctly run.

**Comment by mrg0lden** [comment]
BTW, what about implementing Go modules? This way we can introduce breaking
changes with time when a gain is found.

**Comment by sanae10001** [comment]
@pavelnikolov 
Sorry, my mistake.
The changes of Star Wars example only are legacy codes on commit https://github.com/graph-gophers/graphql-go/pull/182/commits/80ff5e1cd38c344cb5d706fe5ac7f2fec0e0dbef.
Already restore.

**Comment by JohnMaguire** [comment]
@pavelnikolov I'm wondering what the state of this ticket is. As @sanae10001 mentioned, the PR has code to determine if the resolvers are separated or not, and falls back on the existing behavior.

**Comment by maoueh** [comment]
See https://github.com/graph-gophers/graphql-go/pull/421 for a workaround for that, we use this PR in production code, all our resolver's name are prefixed with either `Query`, `Mutation` or `Subscription`.

**Comment by JohnMaguire** [comment]
Excuse my ignorance @pavelnikolov but my impression was that this PR was ready for review but has since generated merge conflicts. Is there a reason it wasn't merged in 2018? Would it be merged if it were cleaned up today?

It's worth noting that the [gqlgen feature comparsion](https://gqlgen.com/feature-comparison/) page points to this issue as a point of distinction for their project.

**Comment by pavelnikolov** [comment]
@sanae10001 I started working on this and will try to add it to the next release. I like your code and I will copy some portion of it.

**Comment by pavelnikolov** [comment]
Closing this in favor of #561

**Pull request closed without merging**
